# Generated by Django 3.0.3 on 2020-03-03 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('undefinedapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='base_health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='char_name',
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
