# Generated by Django 3.0.4 on 2020-03-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undefined_world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
