# Generated by Django 3.0.4 on 2020-03-06 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='ROOM NAME', max_length=50)),
                ('desc', models.CharField(default='ROOM DESCRIPTION', max_length=500)),
                ('NORTH', models.CharField(default='', max_length=150)),
                ('SOUTH', models.CharField(default='', max_length=150)),
                ('EAST', models.CharField(default='', max_length=150)),
                ('WEST', models.CharField(default='', max_length=150)),
                ('map', models.TextField(default='ROOM MAP', max_length=1500)),
            ],
        ),
    ]
