# Generated by Django 3.0.4 on 2020-03-06 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('undefined_world_rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='e_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='n_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='y',
        ),
        migrations.AddField(
            model_name='room',
            name='EAST',
            field=models.CharField(default='EAST', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='NORTH',
            field=models.CharField(default='NORTH', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='SOUTH',
            field=models.CharField(default='SOUTH', max_length=150),
        ),
        migrations.AddField(
            model_name='room',
            name='WEST',
            field=models.CharField(default='WEST', max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
