# Generated by Django 3.0.4 on 2020-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefined_world_rooms', '0002_auto_20200306_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map',
            field=models.CharField(default='ROOM MAP', max_length=500),
        ),
    ]
